name: Manufacturing Development Pipeline
on:
  push:
    branches:
      - mfg-main
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"
        #Set up Maven cache
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: build spring boot
        run: mvn clean install
      - name: copy file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/jewtrade-service.jar
          remote: /home/ubuntu/jewtrade-service.jar
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          password: ${{ secrets.DEV_SSH_PASSWORD }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          password: ${{ secrets.DEV_SSH_PASSWORD }}
          port: ${{ secrets.DEV_PORT }}
          script: sudo systemctl restart jewtrade-jar.service
